[package]
name = "infra-postgres"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
application = { path = "../application" }
domain = { path = "../domain" }
sqlx = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
